import PacificNorthwest from './Assets/120P_PacificNorthwest.jpg'
import SchoolGarden from './Assets/120P_SchoolGarden.jpg'
import GiantPebbles from './Assets/120P_GiantPebbles.jpg'

const layoutData = () => {
    return (
        [
            {
                "id": 1,
                "name": "Pacific Northwest",
                "imageUrl": PacificNorthwest,
                "equipment": {
                    Tank: "ADA 120P", 
                    Lighting: "ADA SOLAR RGB x2",
                    Filter: "EHEIM Classivc 2215 x2",
                },
                "plants": {
                    0: "Java Fern",
                    1: "Java Fern Narrow",
                    2: "Java Fern Windelov",
                    3: "Java Fern Trident",
                    4: "Java Fern Red",
                    5: "Java Fern Sunset",
                    6: "Anubias Pinto",
                    7: "Anubias Petite",
                    8: "Riccardia Chamedryfolia",
                    9: "Bucephalandra Various Sp.",
                    10: "Bolbitis Heudelotii",
                    11: "Crypt Parva",
                    12: "Crypt Wendtii Brown Mini",
                    13: "Crypt Albida Brown",
                    14: "Glossostigma Elatinoides",
                },
                "fauna": {
                    0: "Norman's Lampeye Killifish",
                    1: "Somphongsi Rasbora",
                    2: "Pygmy Corydora",
                    3: "Otocinclus Catfish",
                    4: "Cherry Shrimp",
                    5: "Ramshorn Snails",
                },
                "misc": {
                    "Hardscape 1": "Manzanita Wood",
                    "Hardscape 2": "ADA Yamaya Stone",
                    "Substrate 1": "ADA Amazonia",
                    "Substrate 2": "Pea Gravel",
                    "Light Period": "7 Hours",
                    "CO2": "5-6 BPS, 5 Hours",
                    "Temperature": "22° C",
                    "Water Change": "25%, 2 per week",
                    "TDS": "175",
                }
            },
            {
                "id": 2,
                "name": "School Garden",
                "imageUrl": SchoolGarden,
                "equipment": {
                    Tank: "ADA 120P", 
                    Lighting: "ADA SOLAR RGB x2",
                    Filter: "Oasé Biomaster 600 x2",
                },
                "plants": {
                    0: "Bolbitis Heudelotii",
                    1: "Rotala H'ra",
                    2: "Rotala Macranda",
                    3: "Rotala Bonsai",
                    4: "Hygrophila Araguaia",
                    5: "Java Moss",
                    6: "Eliocharis Acicularis 'Mini'",
                    7: "Aponogeton Boivianus",
                    8: "Aponogeton Longiplumulosus",
                    9: "Cryptocoryne Undulatus 'Red'",
                    10: "Cryptocoryne Wendtii 'Green'",
                    11: "Lagenandra Meeboldii 'Red'",
                    12: "Blyxa Japonica",
                    13: "Lilaeopsis Mauritiana",
                    14: "Riccardia Chamedryfolia",
                    15: "Pogestemon Stellatus",
                    16: "Myriophyllum Mattogrossense",
                    17: "Ranunculus Inundatus",
                    18: "Nymphaea Lotus",
                    19: "Limnophila Aromatica 'Purple'",
                },
                "fauna": {
                    0: "Albino Tiger Barbs",
                    1: "Otocinclus Catfish",
                    2: "Silver Flying Fox",
                    3: "Amano Shrimp",
                    4: "Cherry Shrimp",
                    5: "Common Molly",
                    6: "Ramshorn Snails",
                },
                "misc": {
                    "Hardscape 1": "Manzanita Wood",
                    "Hardscape 2": "ADA Yamaya Stone",
                    "Hardscape 3": "Flat River Stone",
                    "Substrate 1": "ADA Amazonia",
                    "Substrate 2": "Landscaping Sand",
                    "Substrate 3": "Pea Gravel",
                    "Light Period": "7 Hours",
                    "CO2": "3-4 BPS, 5 Hours",
                    "Temperature": "22° C",
                    "Water Change": "25%, 2 per week",
                    "TDS": "100",
                }
            },
            {
                "id": 3,
                "name": "Giant Pebbles",
                "imageUrl": GiantPebbles,
                "equipment": {
                    Tank: "ADA 120P", 
                    Lighting: "ADA SOLAR RGB x2",
                    Filter: "Oasé Biomaster 600 x2",
                },
                "plants": {
                    1: "Aponogeton Longiplumulosus",
                    2: "Pogestemon Stellatus",
                    3: "Nymphaea Lotus",
                    4: "Nymphaea Stellata",
                    5: "Ranunculus Inundatus",
                    6: "Blyxa Japonica",
                    7: "Saggitaria Subulata",
                    8: "Hydrocotyl Triparita",
                    9: "Hygrophila Araguaia",
                    10: "Cryptocoryne Wendtii 'Green'",
                    11: "Rotala Green",
                    12: "Rotala H'ra",
                    13: "Rotala Macranda",
                    14: "Rotala Bonsai",
                    15: "Rotala Rotundifolia",
                    16: "Rotala Wallichii",
                    17: "Java Moss",
                },
                "fauna": {
                    0: "Albino Tiger Barbs",
                    1: "Otocinclus Catfish",
                    2: "Silver Flying Fox",
                    3: "Amano Shrimp",
                    4: "Cherry Shrimp",
                    5: "Common Molly",
                    6: "Ramshorn Snails",
                },
                "misc": {
                    "Hardscape 1": "Manzanita Wood",
                    "Hardscape 2": "ADA Yamaya Stone",
                    "Hardscape 3": "Flat River Stone",
                    "Substrate 1": "ADA Amazonia",
                    "Substrate 2": "Landscaping Sand",
                    "Substrate 3": "Pea Gravel",
                    "Light Period": "7 Hours",
                    "CO2": "3-4 BPS, 5 Hours",
                    "Temperature": "22° C",
                    "Water Change": "25%, 2 per week",
                    "TDS": "100",
                }
            },
        ]
    )
};

export default layoutData